import { EngineResult, UIBlendRecommendation } from '../types/domain';

export function adaptEngineResult(
    result: EngineResult
): UIBlendRecommendation {

    // Deterministic Confidence
    const confidence = result.matchScore ? Math.max(0.1, Math.min(1.0, result.matchScore)) : 0.85;

    return {
        kind: 'blend', // Force kind
        id: result.id || crypto.randomUUID(),
        name: result.name || 'Custom Blend',
        confidence: confidence,
        reasoning: result.reasoning ?? 'Generated by StrainMath™',
        // Fallback for terpeneProfile if missing
        terpeneProfile: result.terpeneWeights || {},
        // Cultivars mapping - ensure safe access
        cultivars: (result.cultivars || []).map((c: any) => ({
            name: c.name || 'Unknown',
            ratio: c.ratio || 0,
            profile: c.profile || 'Hybrid',
            characteristics: c.characteristics || [],
            prominentTerpenes: c.prominentTerpenes || [],
            color: c.color || '#cccccc'
        })),
        // Ensure effects/timeline exist
        effects: result.effects || {
            onset: '5-10m',
            peak: '30-45m',
            duration: '2-3h'
        },
        timeline: result.timeline || []
    };
}
