const { GoogleAuth } = require('google-auth-library');

module.exports = async function handler(request, response) {
    try {
        console.log('[STRAINMATH_GATEWAY] Request started');

        // CORS Headers
        response.setHeader('Access-Control-Allow-Credentials', true);
        response.setHeader('Access-Control-Allow-Origin', '*');
        response.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,POST');
        response.setHeader(
            'Access-Control-Allow-Headers',
            'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
        );

        if (request.method === 'OPTIONS') {
            response.status(200).end();
            return;
        }

        if (request.method !== 'POST') {
            return response.status(200).json({ ok: false, error: 'Method Not Allowed' });
        }

        const { tier1Narrative, toneMode, image, promptOverride, userIntentSummary, blendSummary } = request.body || {};

        const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
        const GCP_PROJECT_ID = process.env.GCP_PROJECT_ID;
        const GCP_SERVICE_ACCOUNT_KEY = process.env.GCP_SERVICE_ACCOUNT_KEY;
        const TAVILY_API_KEY = process.env.TAVILY_API_KEY;
        const region = process.env.GCP_REGION || 'us-central1';

        // CASE 1: VISION MODE (Vertex AI + Tavily)
        if (image) {
            if (!GCP_PROJECT_ID || !GCP_SERVICE_ACCOUNT_KEY) {
                return response.status(200).json({ ok: false, error: 'missing_gcp_config' });
            }

            try {
                const credentials = typeof GCP_SERVICE_ACCOUNT_KEY === 'string' ? JSON.parse(GCP_SERVICE_ACCOUNT_KEY) : GCP_SERVICE_ACCOUNT_KEY;
                const auth = new GoogleAuth({
                    credentials,
                    scopes: 'https://www.googleapis.com/auth/cloud-platform',
                });
                const authClient = await auth.getClient();
                const accessToken = await authClient.getAccessToken();
                const token = accessToken.token;

                const modelId = 'gemini-1.5-flash';
                const endpoint = `https://${region}-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${region}/publishers/google/models/${modelId}:generateContent`;

                const contents = [{
                    role: "user",
                    parts: [
                        { text: "Extract exact product name, brand, and any cannabinoid/terpene percentages from this image. If percentages are missing, emphasize the exact product name so I can search for it." },
                        { inlineData: { mimeType: "image/jpeg", data: image.split(',')[1] || image } }
                    ]
                }];

                const vertexRes = await fetch(endpoint, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                    body: JSON.stringify({ contents, generationConfig: { temperature: 0.1, maxOutputTokens: 1024 } })
                });

                if (!vertexRes.ok) throw new Error(`Vertex Vision Failed: ${await vertexRes.text()}`);
                const vertexData = await vertexRes.json();
                const extractedText = vertexData.candidates?.[0]?.content?.parts?.[0]?.text;

                if (!extractedText) throw new Error("No content generated by Vision API");

                // Check if we need a web search (Tavily)
                let searchResults = "";
                if (TAVILY_API_KEY && (extractedText.toLowerCase().includes("unknown") || !extractedText.match(/\d+%/))) {
                    console.log("[STRAINMATH_IMAGE] Low data density, triggering Tavily search...");
                    const searchRes = await fetch('https://api.tavily.com/search', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            api_key: TAVILY_API_KEY,
                            query: `cannabis product specifications cannabinoids terpenes for: ${extractedText}`,
                            search_depth: "advanced"
                        })
                    });
                    if (searchRes.ok) {
                        const sData = await searchRes.json();
                        searchResults = sData.results?.map(r => r.content).join("\n") || "";
                    }
                }

                // Final refinement with OpenAI
                const refinePrompt = `Based on this label extraction: "${extractedText}" ${searchResults ? `and these search results: "${searchResults}"` : ''}, give me a definitive summary of this product's profile.`;
                const finalRes = await fetch('https://api.openai.com/v1/chat/completions', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${OPENAI_API_KEY}` },
                    body: JSON.stringify({
                        model: 'gpt-4o-mini',
                        messages: [{ role: 'user', content: refinePrompt }],
                        temperature: 0.1
                    })
                });
                const finalData = await finalRes.json();

                return response.status(200).json({ ok: true, data: finalData.choices?.[0]?.message?.content });

            } catch (err) {
                console.error('[STRAINMATH_VISION] Error:', err.message);
                return response.status(200).json({ ok: false, error: 'vision_failed', details: err.message });
            }
        }

        // CASE 2: NARRATIVE MODE (OpenAI - for ALL blends)
        if (tier1Narrative && blendSummary) {
            if (!OPENAI_API_KEY) return response.status(200).json({ ok: false, error: 'missing_openai_key' });

            try {
                const results = await Promise.all(blendSummary.map(async (blend) => {
                    const promptText = `You are StrainMath™, an expert cannabis consultant.
USER REQUEST: "${userIntentSummary || 'Custom experience'}"
BLEND NAME: "${blend.name}"
CULTIVARS: ${blend.cultivars.join(', ')}

YOUR TASK:
1. Create a highly creative, evocative name for this specific blend that DIRECTLY relates to the user's desired outcome.
2. Write a 2-sentence explanation of why this specific synergy of cultivars achieves their goal perfectly.

TONE: ${toneMode || 'neutral'}, professional, confident
FORMAT: Return ONLY JSON: { "newName": "...", "narrative": "..." }`;

                    const res = await fetch('https://api.openai.com/v1/chat/completions', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${OPENAI_API_KEY}` },
                        body: JSON.stringify({
                            model: 'gpt-4o-mini',
                            messages: [{ role: 'user', content: promptText }],
                            temperature: 0.8,
                            response_format: { type: "json_object" }
                        })
                    });
                    const d = await res.json();
                    return JSON.parse(d.choices?.[0]?.message?.content || '{}');
                }));

                return response.status(200).json({ ok: true, narratives: results });

            } catch (err) {
                console.error('[STRAINMATH_NARRATIVE] OpenAI Error:', err.message);
                return response.status(200).json({ ok: false, error: 'narrative_failed' });
            }
        }

        return response.status(200).json({ ok: false, error: 'Invalid Request' });

    } catch (err) {
        console.error('[STRAINMATH_GLOBAL_ERROR]', err.message);
        return response.status(500).json({ ok: false, error: 'server_error', details: err.message });
    }
};
