const { GoogleAuth } = require('google-auth-library');

module.exports = async function handler(request, response) {
    try {
        console.log('[STRAINMATH_VERTEX] Request started');

        // CORS Header Setup
        response.setHeader('Access-Control-Allow-Credentials', true);
        response.setHeader('Access-Control-Allow-Origin', '*');
        response.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,POST');
        response.setHeader(
            'Access-Control-Allow-Headers',
            'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
        );

        if (request.method === 'OPTIONS') {
            response.status(200).end();
            return;
        }

        if (request.method !== 'POST') {
            return response.status(200).json({ ok: false, error: 'Method Not Allowed' });
        }

        // 1. Validate Environment
        const projectId = process.env.GCP_PROJECT_ID;
        const saKey = process.env.GCP_SERVICE_ACCOUNT_KEY;
        const region = process.env.GCP_REGION || 'us-central1';

        if (!projectId || !saKey) {
            console.error('[STRAINMATH_VERTEX] Missing GCP_PROJECT_ID or GCP_SERVICE_ACCOUNT_KEY');
            return response.status(200).json({ ok: false, error: 'missing_gcp_config' });
        }

        const { tier1Narrative, toneMode, image, promptOverride } = request.body || {};

        // 2. Auth Flow
        const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
        const GCP_PROJECT_ID = process.env.GCP_PROJECT_ID;
        const GCP_SERVICE_ACCOUNT_KEY = process.env.GCP_SERVICE_ACCOUNT_KEY;
        const region = process.env.GCP_REGION || 'us-central1';

        if (image) {
            // VISION MODE (Requires Vertex AI)
            if (!GCP_PROJECT_ID || !GCP_SERVICE_ACCOUNT_KEY) {
                return response.status(200).json({ ok: false, error: 'missing_gcp_config' });
            }

            try {
                const credentials = typeof GCP_SERVICE_ACCOUNT_KEY === 'string' ? JSON.parse(GCP_SERVICE_ACCOUNT_KEY) : GCP_SERVICE_ACCOUNT_KEY;
                const auth = new GoogleAuth({
                    credentials,
                    scopes: 'https://www.googleapis.com/auth/cloud-platform',
                });
                const authClient = await auth.getClient();
                const accessToken = await authClient.getAccessToken();
                const token = accessToken.token;

                const modelId = 'gemini-1.5-flash';
                const endpoint = `https://${region}-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${region}/publishers/google/models/${modelId}:generateContent`;

                const contents = [{
                    role: "user",
                    parts: [
                        { text: promptOverride || "Extract every technical detail from this cannabis product label. Focus on Strains, Cannabinoids (THC, CBD, CBG), and Terpenes. Return as a clean data object if possible, or a detailed breakdown." },
                        {
                            inlineData: {
                                mimeType: "image/jpeg",
                                data: image.split(',')[1] || image
                            }
                        }
                    ]
                }];

                const vertexRes = await fetch(endpoint, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${token}`
                    },
                    body: JSON.stringify({
                        contents,
                        generationConfig: { temperature: 0.1, maxOutputTokens: 1024 }
                    })
                });

                if (!vertexRes.ok) {
                    const errorText = await vertexRes.text();
                    throw new Error(`Vertex API Failed: ${errorText}`);
                }

                const data = await vertexRes.json();
                const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;

                if (!resultText) throw new Error("No content generated by Vision API");

                console.log('[STRAINMATH_VISION] Success');
                return response.status(200).json({ ok: true, data: resultText });

            } catch (err) {
                console.error('[STRAINMATH_VISION] Error:', err.message);
                return response.status(200).json({ ok: false, error: 'vision_failed', details: err.message });
            }
        } else if (tier1Narrative) {
            // NARRATIVE MODE (Uses OpenAI/ChatGPT)
            if (!OPENAI_API_KEY) {
                return response.status(200).json({ ok: false, error: 'missing_openai_key' });
            }

            try {
                const { userIntentSummary, blendSummary } = request.body;
                const primaryBlend = blendSummary?.[0] || {};
                const cultivarList = primaryBlend.cultivars || [];
                const cultivarCount = cultivarList.length;

                const promptText = `You are StrainMath™, an expert cannabis consultant explaining a custom blend.

USER REQUEST: "${userIntentSummary || 'Custom experience'}"

BLEND COMPOSITION:
${cultivarList.map((c, i) => `${i + 1}. ${c} (${Math.round(100 / cultivarCount)}%)`).join('\n')}

YOUR TASK:
Write a 2-3 sentence explanation that covers:
1. WHY this specific combination was chosen for their request
2. The ROLE each cultivar plays (anchor, complement, modifier)
3. The SYNERGY between cultivars and expected experience

TONE: ${toneMode || 'neutral'}, professional, confident
STYLE: Natural, conversational, avoid marketing fluff
LENGTH: 2-3 sentences maximum

Write the explanation now:`;

                const openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${OPENAI_API_KEY}`
                    },
                    body: JSON.stringify({
                        model: 'gpt-4o-mini',
                        messages: [{ role: 'user', content: promptText }],
                        temperature: 0.7,
                        max_tokens: 300
                    })
                });

                if (!openaiRes.ok) {
                    const errorText = await openaiRes.text();
                    throw new Error(`OpenAI API Failed: ${errorText}`);
                }

                const data = await openaiRes.json();
                const resultText = data.choices?.[0]?.message?.content?.trim();

                if (!resultText) throw new Error("No content generated by OpenAI");

                console.log('[STRAINMATH_NARRATIVE] OpenAI Success');
                return response.status(200).json({ ok: true, narrative: resultText, data: resultText });

            } catch (err) {
                console.error('[STRAINMATH_NARRATIVE] Error:', err.message);
                // Last ditch fallback to Tier-1
                return response.status(200).json({
                    ok: true,
                    narrative: tier1Narrative?.reasoning || "Balanced match found.",
                    mode: 'fallback'
                });
            }
        } else {
            return response.status(200).json({ ok: false, error: 'Missing Input' });
        }
    } catch (err) {
        console.error('[STRAINMATH_GLOBAL] Error:', err.message);
        return response.status(200).json({ ok: false, error: 'server_error', details: err.message });
    }
};
